<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ServiciosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('servicios')->delete();

        \DB::table('servicios')->insert(array (
            0 =>
            array (
                'id' => 1,
                'nombre' => 'Gravamen o libertad de gravamen hasta por 10 años',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '229.00',
                'urgente' => '458.00',
                'extra_urgente' => '687.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0595',
                'categoria_servicio_id' => 1,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            1 =>
            array (
                'id' => 2,
                'nombre' => 'Gravamen o libertad de gravamen de 10 hasta 20 años',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '280.00',
                'urgente' => '560.00',
                'extra_urgente' => '840.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0610',
                'categoria_servicio_id' => 1,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            2 =>
            array (
                'id' => 3,
                'nombre' => 'Gravamen o libertad de gravamen de más de 20 años',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '561.00',
                'urgente' => '1122.00',
                'extra_urgente' => '1683.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0605',
                'categoria_servicio_id' => 1,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            3 =>
            array (
                'id' => 4,
                'nombre' => 'Exsitencia o inexsitencia de gravamenes o anotaciones preventivas',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '757.00',
                'urgente' => '1514.00',
                'extra_urgente' => '2271.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0620',
                'categoria_servicio_id' => 1,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            4 =>
            array (
                'id' => 5,
                'nombre' => 'Propiedad o negativos de propiedad',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '229.00',
                'urgente' => '458.00',
                'extra_urgente' => '687.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0625',
                'categoria_servicio_id' => 1,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            5 =>
            array (
                'id' => 6,
                'nombre' => 'Propiedad con medidas y linderos',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '280.00',
                'urgente' => '560.00',
                'extra_urgente' => '840.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0630',
                'categoria_servicio_id' => 1,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            6 =>
            array (
                'id' => 7,
                'nombre' => 'Búsqueda de antecedente de 1 a 10',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '727.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0635',
                'categoria_servicio_id' => 1,
                'creado_por' => NULL,
                'actualizado_por' => 1,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 11:30:23',
            ),
            7 =>
            array (
                'id' => 8,
                'nombre' => 'Historía registral hasta 5 antecedentes, por cada uno adicional',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '727.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0640',
                'categoria_servicio_id' => 1,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            8 =>
            array (
                'id' => 9,
            'nombre' => 'Copias certificadas (por página)',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '45.00',
                'urgente' => '90.00',
                'extra_urgente' => '135.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0645',
                'categoria_servicio_id' => 1,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            9 =>
            array (
                'id' => 10,
            'nombre' => 'Copias simples (por página)',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '25.00',
                'urgente' => '50.00',
                'extra_urgente' => '75.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0650',
                'categoria_servicio_id' => 1,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            10 =>
            array (
                'id' => 11,
                'nombre' => 'Reproducciones certificadas de testimonios de escrituras, hasta por 5 hojas',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '485.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0655',
                'categoria_servicio_id' => 1,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            11 =>
            array (
                'id' => 12,
                'nombre' => 'Reproducciones certificadas de testimonios de escrituras por cada hoja',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '485.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0660',
                'categoria_servicio_id' => 1,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            12 =>
            array (
                'id' => 13,
                'nombre' => 'Aclaraciones adminisrativas de inscripciones por cada una',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '467.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0665',
                'categoria_servicio_id' => 1,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            13 =>
            array (
                'id' => 14,
                'nombre' => 'Escrituras constitutivas',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '8.00',
                'ordinario' => '770.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0775',
                'categoria_servicio_id' => 2,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            14 =>
            array (
                'id' => 15,
                'nombre' => 'Actos de emisión de bonos y obligaciones de sociedades mercantiles',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '8.00',
                'ordinario' => '770.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0',
                'categoria_servicio_id' => 2,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            15 =>
            array (
                'id' => 16,
                'nombre' => 'Actas en que se haga constar aumento de capital',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '8.00',
                'ordinario' => '770.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0',
                'categoria_servicio_id' => 2,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            16 =>
            array (
                'id' => 17,
                'nombre' => 'Inscripción de gravámenes relativos a garantías prendiarias',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '8.00',
                'ordinario' => '770.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0',
                'categoria_servicio_id' => 2,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            17 =>
            array (
                'id' => 18,
                'nombre' => 'Cancelaciones de inscripciones de comercio',
                'tipo' => '50%',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '385.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0',
                'categoria_servicio_id' => 2,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            18 =>
            array (
                'id' => 19,
                'nombre' => 'Depósito de balances o inscripciones de los mismos, actas de asambleas de socios o de consejo',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '324.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0',
                'categoria_servicio_id' => 2,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            19 =>
            array (
                'id' => 20,
                'nombre' => 'Actas de disolución o liquidación de sociedades por cada una de las formas codificadas',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '324.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0',
                'categoria_servicio_id' => 2,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            20 =>
            array (
                'id' => 21,
                'nombre' => 'Poderes y sustitución de los mismos',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '517.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0',
                'categoria_servicio_id' => 2,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            21 =>
            array (
                'id' => 22,
                'nombre' => 'Sentencias sobre emancipación para ejercer el comercio, habilitación de edad, licencia de matrimonio y renovación de la misma',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '132.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0',
                'categoria_servicio_id' => 2,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            22 =>
            array (
                'id' => 23,
                'nombre' => 'Incripción y cancelación de contratos de corresponsalias',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '107.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0',
                'categoria_servicio_id' => 2,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            23 =>
            array (
                'id' => 24,
                'nombre' => 'Sentencias sobre declaraciones de quiebra o en que se admita la  liquidación judicial',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '201.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0',
                'categoria_servicio_id' => 2,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            24 =>
            array (
                'id' => 25,
                'nombre' => 'Actos autorizados por el secretario de gobierno',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '691.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0',
                'categoria_servicio_id' => 2,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            25 =>
            array (
                'id' => 26,
                'nombre' => 'Constacia o retificación de documentos y firmas',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '691.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0',
                'categoria_servicio_id' => 2,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            26 =>
            array (
                'id' => 27,
                'nombre' => 'Inscripción de otros documentos en el registro de comercio',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '183.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0',
                'categoria_servicio_id' => 2,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            27 =>
            array (
                'id' => 28,
                'nombre' => 'Por la historia de las inscripcioines de títulos de comercio, por el término que se solicite y hasta cinco antecedentes',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '727.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0',
                'categoria_servicio_id' => 2,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            28 =>
            array (
                'id' => 29,
                'nombre' => 'Inmuebles rústicos',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '5.50',
                'ordinario' => '529.00',
                'urgente' => '1058.00',
                'extra_urgente' => '1587.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0675',
                'categoria_servicio_id' => 3,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            29 =>
            array (
                'id' => 30,
                'nombre' => 'Inmuebles urbanos',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '16.00',
                'ordinario' => '1540.00',
                'urgente' => '3080.00',
                'extra_urgente' => '4620.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0670',
                'categoria_servicio_id' => 3,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            30 =>
            array (
                'id' => 31,
                'nombre' => 'Habitacional sin exder $878,007.50',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '11.00',
                'ordinario' => NULL,
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0680',
                'categoria_servicio_id' => 3,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            31 =>
            array (
                'id' => 32,
                'nombre' => 'Habitacional excediendo $878,007.50',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '11.00',
                'ordinario' => NULL,
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0685',
                'categoria_servicio_id' => 3,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            32 =>
            array (
                'id' => 33,
                'nombre' => 'Fusión de predios',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '462.00',
                'urgente' => '924.00',
                'extra_urgente' => '1386.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0690',
                'categoria_servicio_id' => 3,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            33 =>
            array (
                'id' => 34,
                'nombre' => 'Servidumbres',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '462.00',
                'urgente' => '924.00',
                'extra_urgente' => '1386.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0695',
                'categoria_servicio_id' => 3,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            34 =>
            array (
                'id' => 35,
                'nombre' => 'Plano habitacional recidencial',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '76.00',
                'urgente' => '152.00',
                'extra_urgente' => '228.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0720',
                'categoria_servicio_id' => 3,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            35 =>
            array (
                'id' => 36,
                'nombre' => 'Plano habitacional tipo medio',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '30.00',
                'urgente' => '60.00',
                'extra_urgente' => '90.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0700',
                'categoria_servicio_id' => 3,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            36 =>
            array (
                'id' => 37,
                'nombre' => 'Plano habitacional popular',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '30.00',
                'urgente' => '60.00',
                'extra_urgente' => '90.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0705',
                'categoria_servicio_id' => 3,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            37 =>
            array (
                'id' => 38,
                'nombre' => 'Plano habitacional campestre',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '110.00',
                'urgente' => '220.00',
                'extra_urgente' => '330.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0710',
                'categoria_servicio_id' => 3,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            38 =>
            array (
                'id' => 39,
                'nombre' => 'Plano habitacional rústico',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '76.00',
                'urgente' => '152.00',
                'extra_urgente' => '228.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0715',
                'categoria_servicio_id' => 3,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            39 =>
            array (
                'id' => 40,
                'nombre' => 'Plano industrial y comercial',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '214.00',
                'urgente' => '428.00',
                'extra_urgente' => '642.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0725',
                'categoria_servicio_id' => 3,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            40 =>
            array (
                'id' => 41,
                'nombre' => 'Propiedad en condominio habitacional',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '76.00',
                'urgente' => '152.00',
                'extra_urgente' => '228.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0735',
                'categoria_servicio_id' => 3,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            41 =>
            array (
                'id' => 42,
                'nombre' => 'Propiedad en condominio habitacional - local comercial',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '124.00',
                'urgente' => '248.00',
                'extra_urgente' => '372.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0730',
                'categoria_servicio_id' => 3,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            42 =>
            array (
                'id' => 43,
                'nombre' => 'Subdivisiones',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '76.00',
                'urgente' => '152.00',
                'extra_urgente' => '228.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '1720',
                'categoria_servicio_id' => 3,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            43 =>
            array (
                'id' => 44,
                'nombre' => 'Ratificación de documentos y firmas ante RPP',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '229.00',
                'urgente' => '458.00',
                'extra_urgente' => '687.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0770',
                'categoria_servicio_id' => 3,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            44 =>
            array (
                'id' => 45,
                'nombre' => 'Cuando se aporten bienes inmuebles',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '727.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '1740',
                'categoria_servicio_id' => 3,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            45 =>
            array (
                'id' => 46,
                'nombre' => 'Cuando se aporten bienes distintos',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '727.00',
                'urgente' => '0.00',
                'extra_urgente' => '0.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '1745',
                'categoria_servicio_id' => 3,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            46 =>
            array (
                'id' => 47,
                'nombre' => 'Documentos relativos a grvámenes de bienes inmuebles',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '16.00',
                'ordinario' => '1540.00',
                'urgente' => '3080.00',
                'extra_urgente' => '4620.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '1750',
                'categoria_servicio_id' => 4,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            47 =>
            array (
                'id' => 48,
                'nombre' => 'Cesión de derechos litigosos de crédito',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '16.00',
                'ordinario' => '1540.00',
                'urgente' => '3080.00',
                'extra_urgente' => '4620.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '1755',
                'categoria_servicio_id' => 4,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            48 =>
            array (
                'id' => 49,
                'nombre' => 'División de hipoteca',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '6.00',
                'ordinario' => '577.00',
                'urgente' => '1540.00',
                'extra_urgente' => '1731.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '2140',
                'categoria_servicio_id' => 4,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            49 =>
            array (
                'id' => 50,
                'nombre' => 'Reestructura de créditos o convenios modificatorios',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '462.00',
                'urgente' => '924.00',
                'extra_urgente' => '1386.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '2145',
                'categoria_servicio_id' => 4,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            50 =>
            array (
                'id' => 51,
                'nombre' => 'Convenio modificatorio donde se reforme cualquier claúsula del contrato',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '462.00',
                'urgente' => '924.00',
                'extra_urgente' => '1386.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '2145',
                'categoria_servicio_id' => 4,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            51 =>
            array (
                'id' => 52,
                'nombre' => 'Créditos para la adquisición de vivienda de interés social',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '8.00',
                'ordinario' => '770.00',
                'urgente' => '1540.00',
                'extra_urgente' => '2310.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '2155',
                'categoria_servicio_id' => 4,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            52 =>
            array (
                'id' => 53,
                'nombre' => 'Créditos para la adquisición de vivienda popular',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '10.50',
                'ordinario' => '1010.00',
                'urgente' => '2020.00',
                'extra_urgente' => '3030.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '2540',
                'categoria_servicio_id' => 4,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            53 =>
            array (
                'id' => 54,
                'nombre' => 'Cancelación de documentos relativos a gravámenes de bienes inmuebles',
                'tipo' => '50%',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '770.00',
                'urgente' => '1540.00',
                'extra_urgente' => '2310.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '1760',
                'categoria_servicio_id' => 5,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            54 =>
            array (
                'id' => 55,
                'nombre' => 'Cancelación de cesión de derechos litigosos de crédito',
                'tipo' => '50%',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '770.00',
                'urgente' => '1540.00',
                'extra_urgente' => '2310.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '1755',
                'categoria_servicio_id' => 5,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            55 =>
            array (
                'id' => 56,
                'nombre' => 'Cancelación de grávamen de división de hipoteca',
                'tipo' => '50%',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '289.00',
                'urgente' => '578.00',
                'extra_urgente' => '867.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => 'oendiente',
                'categoria_servicio_id' => 5,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            56 =>
            array (
                'id' => 57,
                'nombre' => 'Cancelación de reestructura de créditos garantizados con bienes inmuebles, o convenios modificatorios a los contratos de crédito',
                'tipo' => '50%',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '265.00',
                'urgente' => '530.00',
                'extra_urgente' => '795.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '0725',
                'categoria_servicio_id' => 5,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            57 =>
            array (
                'id' => 58,
                'nombre' => 'Cancelación de convenio modificatorio donde se reforme cualquier claúsula del contrato',
                'tipo' => '50%',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '231.00',
                'urgente' => '462.00',
                'extra_urgente' => '693.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '1760',
                'categoria_servicio_id' => 5,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            58 =>
            array (
                'id' => 59,
                'nombre' => 'Cancelación de créditos para la adquisición de vivienda de interés social',
                'tipo' => '50%',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '385.00',
                'urgente' => '770.00',
                'extra_urgente' => '1155.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '1760',
                'categoria_servicio_id' => 5,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            59 =>
            array (
                'id' => 60,
                'nombre' => 'Cancelación de créditos para la adquisición de vivienda popular',
                'tipo' => '50%',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '505.00',
                'urgente' => '1010.00',
                'extra_urgente' => '1515.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '1760',
                'categoria_servicio_id' => 5,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            60 =>
            array (
                'id' => 61,
                'nombre' => 'Por la inscripción de varios',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '462.00',
                'urgente' => '924.00',
                'extra_urgente' => '1386.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '1765',
                'categoria_servicio_id' => 6,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            61 =>
            array (
                'id' => 62,
                'nombre' => 'Testimonios notariales, y los avisos preventivos',
                'tipo' => 'fija',
                'estado' => 'activo',
                'umas' => '0.00',
                'ordinario' => '462.00',
                'urgente' => '924.00',
                'extra_urgente' => '1386.00',
                'operacion_principal' => '2403',
                'operacion_parcial' => '1765',
                'categoria_servicio_id' => 6,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
            62 =>
            array (
                'id' => 63,
                'nombre' => 'Cuando se trate de uno o hasta cinco tomos o libros índice',
                'tipo' => 'uma',
                'estado' => 'activo',
                'umas' => '1',
                'ordinario' => '104.00',
                'urgente' => null,
                'extra_urgente' => null,
                'operacion_principal' => '2403',
                'operacion_parcial' => '1765',
                'categoria_servicio_id' => 1,
                'creado_por' => NULL,
                'actualizado_por' => NULL,
                'created_at' => '2023-03-31 10:52:19',
                'updated_at' => '2023-03-31 10:52:19',
            ),
        ));


    }
}
